# Generated by Django 5.2.17 on 2026-09-16 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.TextField(max_length=100)),
                ('port', models.TextField(max_length=100)),
                ('value', models.CharField(max_length=100, null=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_port', to='segmentAPI.canvas')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_port', to='segmentAPI.canvas')),
            ],
        ),
    ]
