# Generated by Django 5.2.17 on 2026-09-16 08:54

from django.db import migrations

def seed_initial_data(apps, schema_editor):
    Canvas = apps.get_model('segmentAPI', 'Canvas')

    port_1a = Canvas.objects.create(
        node='1',
        port='1a',
        value=100,
        source=None,
        target=None,
    )

    port_2a = Canvas.objects.create(
        node='2',
        port='2a',
        value=90,
        source=None,
        target=None,
    )

    port_2b = Canvas.objects.create(
        node='2',
        port='2b',
        value=130,
        source=None,
        target=None,
    )

    port_3a = Canvas.objects.create(
        node='3',
        port='3a',
        value=150,
        source=None,
        target=None,
    )

    port_4a = Canvas.objects.create(
        node='4',
        port='4a',
        value=70,
        source=None,
        target=None,
    )

    port_5a = Canvas.objects.create(
        node='5',
        port='5a',
        value=160,
        source=None,
        target=None,
    )

    port_6a = Canvas.objects.create(
        node='6',
        port='6a',
        value=None,
        source=None,
        target=None,
    )

    port_6b = Canvas.objects.create(
        node='6',
        port='6b',
        value=None,
        source=None,
        target=None,
    )

    port_6c = Canvas.objects.create(
        node='6',
        port='6c',
        value=None,
        source=None,
        target=None,
    )

    port_7a = Canvas.objects.create(
        node='7',
        port='7a',
        value=None,
        source=None,
        target=None,
    )

    port_7b = Canvas.objects.create(
        node='7',
        port='7b',
        value=None,
        source=None,
        target=None,
    )

    port_7c = Canvas.objects.create(
        node='7',
        port='7c',
        value=None,
        source=None,
        target=None,
    )

    port_8a = Canvas.objects.create(
        node='8',
        port='8a',
        value=200,
        source=None,
        target=None,
    )

    port_9a = Canvas.objects.create(
        node='9',
        port='9a',
        value=120,
        source=None,
        target=None,
    )

    port_10a = Canvas.objects.create(
        node='10',
        port='10a',
        value=80,
        source=None,
        target=None,
    )

    port_11a = Canvas.objects.create(
        node='11',
        port='11a',
        value=150,
        source=None,
        target=None,
    )

    port_11b = Canvas.objects.create(
        node='11',
        port='11b',
        value=100,
        source=None,
        target=None,
    )

    port_11c = Canvas.objects.create(
        node='11',
        port='11c',
        value=300,
        source=None,
        target=None,
    )

    port_11d = Canvas.objects.create(
        node='11',
        port='11d',
        value=60,
        source=None,
        target=None,
    )

    port_12a = Canvas.objects.create(
        node='12',
        port='12a',
        value=250,
        source=None,
        target=None,
    )

    port_12b = Canvas.objects.create(
        node='12',
        port='12b',
        value=200,
        source=None,
        target=None,
    )

    port_12c = Canvas.objects.create(
        node='12',
        port='12c',
        value=400,
        source=None,
        target=None,
    )

    port_1a.target = port_2a
    port_1a.save()

    port_2a.source = port_1a
    port_2a.save()

    port_2b.target = port_6b
    port_2b.save()

    port_3a.target = port_6a
    port_3a.save()

    port_4a.target = port_7a
    port_4a.save()

    port_5a.target = port_7b
    port_5a.save()

    port_6a.source = port_3a
    port_6a.save()

    port_6b.source = port_2b
    port_6b.save()

    port_6c.target = port_12a
    port_6c.save()

    port_7a.source = port_4a
    port_7a.save()

    port_7b.source = port_5a
    port_7b.save()

    port_7c.target = port_12b
    port_7c.save()

    port_8a.target = port_11a
    port_8a.save()

    port_9a.target = port_11b
    port_9a.save()

    port_10a.target = port_11d
    port_10a.save()

    port_11a.source = port_8a
    port_11a.save()

    port_11b.source = port_9a
    port_11b.save()

    port_11c.target = port_12a
    port_11c.save()

    port_11d.source = port_10a
    port_11d.save()

    port_12a.source = port_6c
    port_12a.save()

    port_12b.source = port_7c
    port_12b.save()

    port_12c.source = port_11c
    port_12c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('segmentAPI', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_initial_data)
    ]
