# Generated by Django 5.2.17 on 2026-09-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentAPI', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='value',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
