# Generated by Django 5.2.17 on 2026-09-18 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentAPI', '0003_alter_canvas_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='source',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_port', to='segmentAPI.canvas'),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='target',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_port', to='segmentAPI.canvas'),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
